"""adicionando notadepagamento_id

Revision ID: c82c6f5d536a
Revises: df405d86a773
Create Date: 2023-10-01 19:27:10.913517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c82c6f5d536a'
down_revision: Union[str, None] = 'df405d86a773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devolucao', sa.Column('notaDePagamento_id', sa.Integer(), nullable=True))

    op.create_foreign_key(None, 'devolucao', 'notadepagamento', ['notaDePagamento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devolucao', type_='foreignkey')

    op.drop_column('devolucao', 'notaDePagamento_id')
    # ### end Alembic commands ###
