"""datetime no emprestimo

Revision ID: 099c6456c06f
Revises: 1c03b39ffa4e
Create Date: 2023-09-30 18:07:30.735943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '099c6456c06f'
down_revision: Union[str, None] = '1c03b39ffa4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emprestimo', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emprestimo', 'created_at')
    # ### end Alembic commands ###
