"""adicionando devolucao

Revision ID: 5aaeecfa7128
Revises: b917e9f9f8e1
Create Date: 2023-10-01 00:53:03.873365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5aaeecfa7128'
down_revision: Union[str, None] = 'b917e9f9f8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devolucao',
    sa.Column('emprestimo_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['emprestimo_id'], ['emprestimo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devolucao')
    # ### end Alembic commands ###
