"""enum teste

Revision ID: d4a74ccba648
Revises: ac885f826bf1
Create Date: 2023-10-17 15:14:39.706962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd4a74ccba648'
down_revision: Union[str, None] = 'ac885f826bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    meu_enum = postgresql.ENUM('ADMIN', 'CLIENTE', name='role')
    meu_enum.create(op.get_bind(), checkfirst=False)
    op.add_column('usuario', sa.Column('tipo', meu_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'tipo')
    # ### end Alembic commands ###
