"""adicionando notadepagamento

Revision ID: df405d86a773
Revises: 5aaeecfa7128
Create Date: 2023-10-01 19:22:06.011766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'df405d86a773'
down_revision: Union[str, None] = '5aaeecfa7128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notadepagamento',
    sa.Column('preco', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devolucao', 'emprestimo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('notadepagamento')
    # ### end Alembic commands ###
